### PR TITLE
Kill /schedule-session with fire

### PR DESCRIPTION
**Pull request by lionsdwarf**
https://giphy.com/gifs/game-of-thrones-fire-9OddWPdBh2H96

### CODE REVIEW

**Comment by lionsdwarf** [comment]
https://giphy.com/gifs/game-of-thrones-fire-9OddWPdBh2H96

**Comment by craigspaeth** [comment]
LGTM! But there's a whole backend part to this as well, such as how we [generate a JWT](https://github.com/findOctave/cortex/blob/master/apps/api/jobs/notifications/mapper.js#L45) in the email prompt, and check [the local JWT](https://github.com/findOctave/cortex/blob/master/apps/api/lib/jwt-context.js#L12) to see if it was generated from our app. It'd be nice to kill that off too and be consolidated on Auth0 based JWTs.

**Comment by lionsdwarf** [comment]
I've updated the PR as it relates to the `jwt`s.

Since I've heard murmurings about killing Onboard Stage with fire, I'm punting the `notifications` cleanup for now...

**Comment by craigspaeth** [comment]
👍 thanks!

**Pull request merged**
