### PR TITLE
Support hiding location in appt confirmation emails from ICS file by using appointmentType ids in airtable

### PR DESCRIPTION
**Pull request by TMcMeans**
Screen Shot 2019-08-20 at 2 32 13 PM

Our solution made the location property value conditional based on apptType category. All email confirmations are "turned on" only by adding an id to the appointmentTypes column in Airtable. 

Production on Airtable has email confirmation notification settings for consults and in-person intakes. I'm not sure which ones are supposed to be virtual. Should we add appointmentTypes ids to all the relevant notifications in production? When you say "turn on" for consults & coaching do you mean add an appointmentTypes id to each of their notifications settings on Airtable? Clients won't receive notifications without it.

### CODE REVIEW

**Comment by lionsdwarf** [comment]
Code looks good! Let's also please include a unit test for the `isVirtual` function. And on second thought...maybe that function should be called `isVirtualLocation`. What do you think ?

**Comment by craigspaeth** [comment]
👏 well done—easy peasy!

**Comment by TMcMeans** [comment]
I like that idea! I'll rename the function and add a unit test for it.

**Comment by TMcMeans** [comment]
Unit tests are up! Also, organized the notifications.test.js file to group unit tests to make the file more readable. Let me know what ya'll think!

**Comment by craigspaeth** [comment]
👏 nice updates!

**Pull request merged**
