### PR TITLE
Generic form component that renders stripe form only after stripe.js loads

### PR DESCRIPTION
**Pull request by lionsdwarf**

### CODE REVIEW

**Comment by craigspaeth** [comment]
👏 well done!

FYI: Feel free to send PRs to Tanjie or Colton if I’m away. Even just a 2nd pair of eyes to say “lgtm” is better at catching bugs than no code review.

**Comment by lionsdwarf** [comment]
👍🏽Tanjie and I paired on this so we merged it. Should we leave you off as
"reviewer" during PTO?

**Comment by craigspaeth** [comment]
Ah! Cool cool 👍 Pairing = code review too! Sorry for jumping to conclusions 😛 Np, feel free to keep me on PRs while OOO. Well done you two 🤘

**Comment by lionsdwarf** [comment]
🤘🤘🤘

**Pull request merged**
